name: Pull Request

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  types:
    runs-on: ubuntu-latest
    env:
      BITTE_API_KEY: fake-api-key
      NEAR_PK: fake-key
      NEXT_PUBLIC_ACCOUNT_ID: fake-account
      CRON_SECRET: fake-secret

    steps:
      - uses: actions/checkout@v5

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint, Typecheck & Build
        run: |
          pnpm lint
          pnpm types
          pnpm build
